name: CI

on:*
  pull_request:

jobs:

  validat*:

    runs-on: ubuntu-latest

   *steps:

      - name: Checkout
   *    uses: actions/checkout@v4

   *  - name: Install Python
        u*es: actions/setup-python@v5
      * with:
          python-version: "*.11"

      - name: Install depend*ncies
        run: |
          pip*install -r requirements.txt

     *- name: Install Databricks CLI
   *    uses: databricks/setup-cli@mai*

      - name: Run Tests
        *un: pytest

      - name: Validate*Bundle
        run: databricks bun*le validate
