resources:
  pipelines:
    orders_pipeline:
      name: orders_pipeline01

      catalog: demo_schema
      schema: default

      serverless: true

      development: true
      continuous: true

      libraries:
        - file:
            path: ../src/pipelines/orders_pipeline.py
