resources:

  jobs:

    orders_workflow:

      name: orders_workflow

      tasks:

        - task_key: run_orders_pipeline

          pipeline_task:
            pipeline_id: ${resources.pipelines.orders_pipeline.id}
